# Base configuration for UT-HAR experiments
dataset:
  name: UT-HAR
  root: ./data/UTD-HAR
  num_classes: 7
  seq_length: 250
  num_features: 90
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

model:
  input_dim: 90
  seq_len: 250
  hidden_dim: 256
  dropout: 0.3

training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler:
    type: cosine
    warmup_epochs: 5
  
logging:
  tensorboard: true
  save_frequency: 10
  log_frequency: 50

seed: 42
device: cuda
num_workers: 0