x_train: 'UT_HAR/X_train.csv'
y_train: 'UT_HAR/y_train.csv'
x_val: 'UT_HAR/X_val.csv'
y_val: 'UT_HAR/y_val.csv'
x_test: 'UT_HAR/X_test.csv'
y_test: 'UT_HAR/y_test.csv'
num_classes: 7
batch_size: 16
lr: 0.0003
epochs: 40
corruption: 0.2      # Drop 20% packets during training
jitter: true
corruption_levels: [0.0, 0.1, 0.2, 0.4, 0.6]
